### ISSUE TITLE
Memory errors when referencing mocks in dealloc

### ISSUE THREAD

**Issue by cerihughes** [jonreid/OCMockito#107]
Hi Jon,

I'm having some problems when using OCMockito with mock objects that are invoked in dealloc. This is related to another issue that was raised about memory leaks in tests (https://github.com/jonreid/OCMockito/issues/67).

My scenario is similar to that outlined in the above issue - I  call reset on the mock to break the retain cycle between the mock and my SUT and this means that dealloc is called on my SUT. However, as part of my SUT's dealloc method, I have a call to an object that is mocked. If I understand OCMockito correctly, this then creates another strong reference from the mock to the object that's being dealloced causing a crash in destruction.

Consider the following code:

*ObservableObject.h:*
```
@protocol ObjectObserver <NSObject>
- (void)someMethod;
@end

@interface ObservableObject : NSObject
- (void)addObserver:(id<ObjectObserver>)observer;
- (void)removeObserver:(id<ObjectObserver>)observer;
@end
```
*ObservableObject.m:*
```
@implementation ObservableObject
- (void)addObserver:(id<ObjectObserver>)observer {}
- (void)removeObserver:(id<ObjectObserver>)observer{}
@end
```
*ObservingObject.h:*
```
@class ObservableObject;

@interface ObservingObject : NSObject
- (instancetype)initWithObservableObject:(ObservableObject *)observableObject;
@end
```
*ObservingObject.m:*
```
@interface ObservingObject () <ObjectObserver>
@property (nonatomic, strong) ObservableObject *observableObject;
@end

@implementation ObservingObject

- (instancetype)initWithObservableObject:(ObservableObject *)observableObject
{
    if (!(self = [super init])) {
        return nil;
    }

    _observableObject = observableObject;
    [_observableObject addObserver:self];

    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(someNotificationHappened:)
                                                 name:@"SomeNotificationName"
                                               object:nil];

    return self;
}

- (void)dealloc
{
    [_observableObject removeObserver:self];
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}

- (void)someMethod {}
- (void)someNotificationHappened:(NSNotification *)notification {}

@end
```
*ObservingObjectTest.m*
```
#import <XCTest/XCTest.h>

#define MOCKITO_SHORTHAND
#import <OCMockitoIOS/OCMockitoIOS.h>
#define HC_SHORTHAND
#import <OCHamcrestIOS/OCHamcrestIOS.h>

#import "ObservableObject.h"
#import "ObservingObject.h"

@interface ObservingObjectTest : XCTestCase

@property (nonatomic, strong) ObservableObject *mockObservableObject;
@property (nonatomic, strong) ObservingObject *observingObject;

@end

@implementation ObservingObjectTest

- (void)setUp
{
    [super setUp];

    self.mockObservableObject = mock([ObservableObject class]);
    self.observingObject = [[ObservingObject alloc] initWithObservableObject:self.mockObservableObject];
}

- (void)tearDown
{
    [super tearDown];

    [(id)self.mockObservableObject reset];
    self.mockObservableObject = nil;
    self.observingObject = nil;
}

- (void)testExample {}
- (void)testExample2 {}
```

Note that if I _don't_ reset the mock in the test's tearDown method, dealloc isn't called, so the objects leak and will still respond to the NSNotifications fired from the NSNotificationCenter. If I _do_ reset the mock, I get memory destruction errors.

A solution could be to no longer capture strong references on the mock after reset is called, but I haven't tried this out. Another solution could be to explicitly add startMocking and stopMocking calls to the mock but this feels a bit heavy handed.

Do you have any advice on how to get mocks working for this use case? Please let me know if you have any trouble reproducing it and I'll help however I can.

Thanks,

Ceri

**Comment by 72lions** [comment]
I definitely have the same problem! Any ideas?

**Comment by kenji21** [comment]
We were facing similar issue, a non-deallocation (leak) of objects that were given as parameter method of a mock. That was a pain to find the issue (running single test works, multiple one fails), 3 hours later we found that we should call reset.

We were using verify() on the mock object, which validate that each parameter are same as one passed to verify, maybe that's why they are retained and you need to call reset.

Maybe reset should be added to more samples whitin Readme, and in complement to the "Fixing retain cycles" part.

**Comment by jonreid** [comment]
Thank you for the sample code and detailed diagnosis. I managed to fix the problem by having reset do more: by having it not do any of the `-forwardInvocation:` stuff anymore. So really, it's no longer "reset", it's "stop mocking".

The idea of reset itself — to clear out all stubbing and continue with fresh stubs on the same mock — is something I'd want to discourage. Since it was really driven by the need to clear out retain cycles on already retained arguments, let me replace it altogether with `stopMocking()`.
