### ISSUE TITLE
Mockito Functionality: InOrder and Spy

### ISSUE THREAD

**Issue by hartbit** [jonreid/OCMockito#6]
Hi, I'm really missing the inOrder and spy (partial mock) functionality. Just wanted to voice my opinion in case you plan to implement them.

Thanks!

**Comment by top-master** [comment]
Seems spy (or partial mocking) features were added, but **got removed just few months later!**
From [PR #41](https://github.com/jonreid/OCMockito/pull/41#issuecomment-29685857):
>Just making a spy causes the call stack to overflow (at least on iOS, I haven't tried Mac).

# Anyone still interested in spy-features, try [Cuckoo](https://github.com/Brightify/Cuckoo) for Swift
They have no call-stack issues, simply because they auto-generate mock using `Run Script` in `Build Phases`
(which for example, would generate `MockMyClass` for `MyClass`).

Their README makes it look like you need to add each file separately into `Run script`,
but one could simply use directory-recursion instead!!

It's for Swift but "`#import <Cuckoo/Cuckoo-Swift.h>`" may work in Obj-C, if not, fork it and add a lot of `@objc` 😭 
(Yet another pod which promises Java's Mockito style,
but with spy-feature and probably more, so maybe efforts should merge instead of competing).
